name: Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths-ignore:
      - 'docs/**'
      - 'external/**'
      - '**.md'
      - '**.sh'
    branches: [ main ]
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'external/**'
      - '**.md'
    branches: [ main ]

jobs:
  # Build the source file with maven
  build:

    runs-on: ubuntu-latest


    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set up java 1/8
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Cache maven packages
      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Build the source code
      - name: Build with Maven
        run: mvn -B clean package

  run_tests:
  
    runs-on: ubuntu-latest
    needs: [ build ]
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up Java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml


